### ISSUE TITLE
Converting various recent Windows Server builds fails

### ISSUE THREAD

**Issue by LillyWho** [gus33000/UUPMediaCreator#165]
```
[19:59:18][Information] [CreatingWindowsInstaller][100%] Updating 132 files in boot.wim...
ManagedWimLib.WimLibException: [Open] [ERROR] Can't open "C:\Users\ADMINI~1.SIN\AppData\Local\Temp\1689011710197\MediaRoot\sources\install.esd" read-only: No such file or directory
   at ManagedWimLib.WimLibException.CheckErrorCode(ErrorCode ret)
   at ManagedWimLib.Wim.OpenWim(String wimFile, OpenFlags openFlags)
   at UnifiedUpdatePlatform.Imaging.NET.WimImaging.GetWIMInformation(String wimFile, WIM& wimInformationObject)
[19:59:19][   Error   ] An error occured!
[19:59:19][   Error   ] An error occurred while creating the ISO.```

Invoked commands: 
```
.\UUPDownload.exe -s DatacenterServer -v 10.0.25350.1 -r External -b ReleasePreview -c zn_release -t amd64 -l en-US
.\UUPMediaConverter.exe -u .\10.0.25398.1.zn_release.230610-1204_amd64fre_27c746050640\ -i winserver_preview.iso -l en-US -e DatacenterServer```

There is a previous error in the output related to WIM files; perhaps this is relevant:
```
[19:55:08][Information] [ReadingMetadata] Acquiring Edition Upgrades
ManagedWimLib.WimLibException: [PathDoesNotExist] [ERROR] Path "$filehashes$.dat" does not exist in WIM image 1
   at ManagedWimLib.WimLibException.CheckErrorCode(ErrorCode ret)
   at ManagedWimLib.Wim.ExtractPath(Int32 image, String target, String path, ExtractFlags extractFlags)
   at UnifiedUpdatePlatform.Imaging.NET.WimImaging.ExtractFileFromImage(String wimFile, Int32 imageIndex, String fileToExtract, String destination)
ManagedWimLib.WimLibException: [PathDoesNotExist] [ERROR] Path "$filehashes$.dat" does not exist in WIM image 1
   at ManagedWimLib.WimLibException.CheckErrorCode(ErrorCode ret)
   at ManagedWimLib.Wim.ExtractPath(Int32 image, String target, String path, ExtractFlags extractFlags)
   at UnifiedUpdatePlatform.Imaging.NET.WimImaging.ExtractFileFromImage(String wimFile, Int32 imageIndex, String fileToExtract, String destination)```

The issue persists across both versions that I've tried, that being ``10.0.25398.1.zn_release.230610-1204_amd64fre_27c746050640`` and ``10.0.25363.1.zn_release.230505-1545_amd64fre_e30a1fb0fe5e``

**Comment by LillyWho** [comment]
Issue also persists with the latest retail version of Server 2022

**Comment by LillyWho** [comment]
Turns out, omitting the edition flag has the ISO creation succeed for Server 2022
