### ISSUE TITLE
Issues downloading 10.0.22635.2419 and ,2483 with newest 3.1.9.0

### ISSUE THREAD

**Issue by mrpijey** [gus33000/UUPMediaCreator#184]
```
[13:20:37][Information] Checking for updates...
[13:20:39][Information] Found 1 update(s):
[13:21:35][Information] 0: Title: Cumulative Update for Windows 11 Insider Preview (10.0.22635.2419) (KB5031463)
[13:21:35][Information] 0: Description: Install this update to resolve issues in Windows. For a complete listing of the issues that are included in this update, see the associated Microsoft Knowledge Base article for more information. After you install this item, you may have to restart your computer.
[13:21:35][Information] Title: Cumulative Update for Windows 11 Insider Preview (10.0.22635.2419) (KB5031463)
[13:21:35][Information] Description: Install this update to resolve issues in Windows. For a complete listing of the issues that are included in this update, see the associated Microsoft Knowledge Base article for more information. After you install this item, you may have to restart your computer.
[13:21:35][Information] Gathering update metadata...
[13:21:42][Information] Build String: 10.0.22635.2419 (ni_release_svc_betaflt_prod1.230928-1741)
[13:21:42][Information] Languages: zh-cn, bg-bg, cs-cz, da-dk, de-de, el-gr, en-gb, en-us, es-es, et-ee, fi-fi, fr-fr, hr-hr, hu-hu, it-it, lt-lt, lv-lv, nb-no, nl-nl, pl-pl, pt-pt, ro-ro, sk-sk, sl-si, sv-se, ar-sa, es-mx, fr-ca, he-il, ja-jp, ko-kr, pt-br, ru-ru, sr-latn-rs, th-th, tr-tr, uk-ua, zh-tw
[13:21:42][   Error   ] Something happened.
[13:21:42][   Error   ] One or more errors occurred. (Value cannot be null. (Parameter 'source'))
[13:21:42][   Error   ]    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at UUPDownload.DownloadRequest.Process.ParseDownloadOptions(DownloadRequestOptions opts)
   at UUPDownload.Program.<>c__DisplayClass2_0.<Main>b__4()
   at UUPDownload.Program.WrapAction(Action a)
[13:21:42][   Error   ] Value cannot be null. (Parameter 'source')
[13:21:42][   Error   ]    at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
   at UnifiedUpdatePlatform.Services.WindowsUpdate.Downloads.UpdateUtils.BuildListOfPayloads(HashSet`1 compDBs, String Edition, String Language)
   at UnifiedUpdatePlatform.Services.WindowsUpdate.Downloads.UpdateUtils.ProcessUpdateAsync(UpdateData update, String pOutputFolder, MachineType MachineType, IProgress`1 generalDownloadProgress, String Language, String Edition, Boolean WriteMetadata, Boolean UseAutomaticDownloadFolder, Int32 downloadThreads)
   at UUPDownload.DownloadRequest.Process.ProcessUpdateAsync(UpdateData update, String pOutputFolder, MachineType MachineType, String Language, String Edition, Boolean WriteMetadata)
   at UUPDownload.DownloadRequest.Process.CheckAndDownloadUpdates(OSSkuId ReportingSku, String ReportingVersion, MachineType MachineType, String FlightRing, String FlightingBranchName, String BranchReadinessLevel, String CurrentBranch, String ReleaseType, Boolean SyncCurrentVersionOnly, String ContentType, String Mail, String Password, String OutputFolder, String Language, String Edition)
```

**Comment by gus33000** [comment]
Should be fixed with the 3.9.1.0 release
