### ISSUE TITLE
How is command for EntG

### ISSUE THREAD

**Issue by truefriend-cz** [gus33000/UUPMediaCreator#19]
Hi. How is command for latest Enterprise G?

This line ended without downloading
`uupdownload -s Enterprise G -v 10.0.19043.867 -r External -c 21h1_release -t amd64 -l en-US -o Download`

**Comment by truefriend-cz** [comment]
Thnak you very much... and i will get next problem on ISO creating.

This command:

`for /f %f in ('dir /b .\Download\') do uupmediaconvertercli %CD%\Download\%f Windows_10_EnterpriseG_AMD64_English.iso en-US`

Ended this error:
```
[20:37:42][  Warning  ] WARNING: This tool does NOT currently integrate updates into the finished media file. Any UUP set with updates (KBXXXXX).MSU/.CAB will not have the update integrated.
[20:37:42][Information] [ReadingMetadata] Acquiring Composition Databases
[20:37:44][Information] [ReadingMetadata] Acquiring Base Editions
[20:37:44][Information] [ReadingMetadata] Adding Base Editions to the conversion plan
[20:37:44][Information] [ReadingMetadata] Acquiring Edition Upgrades
Unable to find native library [D:\Temp\9\runtimes\win-x64\native\libwim-15.dll].
[20:37:44][Information] [ReadingMetadata] Acquiring Edition Downgrades
[20:37:45][Information] [ReadingMetadata] Building Targets
[20:37:45][Information] [ReadingMetadata] -> Name: core, Availability: Canonical
[20:37:45][Information] [ReadingMetadata] -> Name: coren, Availability: Canonical
[20:37:45][Information] [ReadingMetadata] -> Name: PPIPro, Availability: Canonical
[20:37:45][Information] [ReadingMetadata] -> Name: professional, Availability: Canonical
[20:37:45][Information] [ReadingMetadata]    Destructive Edition Upgrade Targets:
[20:37:45][Information] [ReadingMetadata]    -> Name: EnterpriseEval, Availability: EditionPackageSwap
[20:37:45][Information] [ReadingMetadata]    -> Name: EnterpriseG, Availability: EditionPackageSwap
[20:37:45][Information] [ReadingMetadata] -> Name: professionaln, Availability: Canonical
[20:37:45][Information] [ReadingMetadata]    Destructive Edition Upgrade Targets:
[20:37:45][Information] [ReadingMetadata]    -> Name: EnterpriseGN, Availability: EditionPackageSwap
[20:37:45][Information] [ReadingMetadata]    -> Name: EnterpriseNEval, Availability: EditionPackageSwap
[20:37:45][Information] [ReadingMetadata] Enumerating files
[20:37:45][Information] [ReadingMetadata] Looking up Composition Database in order to find a Base ESD image appropriate for building windows setup files.
Unable to find native library [D:\Temp\9\runtimes\win-x64\native\libwim-15.dll].
[20:37:47][   Error   ] An error occured!
[20:37:47][   Error   ] System.TypeInitializationException: The type initializer for 'MediaCreationLib.Installer.WindowsInstallerBuilder' threw an exception.
 ---> System.PlatformNotSupportedException: Unable to find native library [D:\Temp\9\runtimes\win-x64\native\libwim-15.dll].
   at Imaging.WIMImaging.InitNativeLibrary()
   at Imaging.WIMImaging..ctor()
   at MediaCreationLib.Installer.WindowsInstallerBuilder..cctor()
   --- End of inner exception stack trace ---
   at MediaCreationLib.Installer.WindowsInstallerBuilder.CreateSetupMediaRoot(String BaseESD, String OutputPath, ProgressCallback ProgressCallback)
   at MediaCreationLib.Installer.WindowsInstallerBuilder.BuildSetupMedia(String BaseESD, String OutputWinREPath, String MediaPath, WimCompressionType compressionType, Boolean RunsAsAdministrator, String LanguageCode, ProgressCallback progressCallback)
   at MediaCreationLib.Installer.SetupMediaCreator.CreateSetupMedia(String UUPPath, String LanguageCode, String OutputMediaPath, String OutputWindowsREPath, CompressionType CompressionType, ProgressCallback progressCallback)
   at MediaCreationLib.MediaCreator.CreateISOMediaAdvanced(String ISOPath, String UUPPath, String LanguageCode, Boolean IntegrateUpdates, CompressionType CompressionType, ProgressCallback progressCallback)
   at UUPMediaConverterCli.Program.Main(String[] args)
The end
```

**Comment by Tekkie-Boy** [comment]
`D:\Temp\9\runtimes\win-x64\native\libwim-15.dll`

Note the folder structure.
If the file libwim-15.dll is in the root directory of uupdownloader, the process with the UUP Media Converter fails with this error message.

**Comment by truefriend-cz** [comment]
Thank you very much Tekkie-Boy. This is work perfect.
