### ISSUE TITLE
0.3.0.3 UUPMediaConverterCli System.PlatformNotSupportedException: Unable to find native library [libwim-15.dll]

### ISSUE THREAD

**Issue by andrewbaker-uk** [gus33000/UUPMediaCreator#23]
When attempting to run the following command line from a powershell window

`.\UUPMediaConverterCli.exe C:\ImageFactory\10.0.21354.1.co_release.210402-1630_amd64fre_14f1b83047b0\ "C:\imagefactory\10.0.21354.1 (co_release.210402-1630).iso" en-gb professional`

I get an error where UUPMediaConverterCli.exe is unable to find the native library libwim-15.dll

`[23:33:06][   Error   ] An error occured!
[23:33:06][   Error   ] System.TypeInitializationException: The type initializer for 'MediaCreationLib.Installer.WindowsInstallerBuilder' threw an exception.
 ---> System.PlatformNotSupportedException: Unable to find native library [C:\Users\Andre\Downloads\win-x64\runtimes\win-x64\native\libwim-15.dll].
   at Imaging.WIMImaging.InitNativeLibrary()
   at Imaging.WIMImaging..ctor()
   at MediaCreationLib.Installer.WindowsInstallerBuilder..cctor()
   --- End of inner exception stack trace ---
   at MediaCreationLib.Installer.WindowsInstallerBuilder.CreateSetupMediaRoot(String BaseESD, String OutputPath, ProgressCallback ProgressCallback)
   at MediaCreationLib.Installer.WindowsInstallerBuilder.BuildSetupMedia(String BaseESD, String OutputWinREPath, String MediaPath, WimCompressionType compressionType, Boolean RunsAsAdministrator, String LanguageCode, ProgressCallback progressCallback)
   at MediaCreationLib.Installer.SetupMediaCreator.CreateSetupMedia(String UUPPath, String LanguageCode, String OutputMediaPath, String OutputWindowsREPath, CompressionType CompressionType, ProgressCallback progressCallback)
   at MediaCreationLib.MediaCreator.CreateISOMedia(String ISOPath, String UUPPath, String Edition, String LanguageCode, Boolean IntegrateUpdates, CompressionType CompressionType, ProgressCallback progressCallback)
   at UUPMediaConverterCli.Program.Main(String[] args)`

This is caused by the release download not having the correct path in the zip, as runtimes\win-x64\native\ doesn't exist.

The command does run if the runtimes\win-x64\native path exists and the file(s) exist. I copied over everything from the zip to the location. 

```
PS C:\utils\UUPMediaCreator> tree /F
Folder PATH listing
Volume serial number is D0D2-C682
C:.
│   aria2c.exe
│   clrcompression.dll
│   clrjit.dll
│   CompDB.NET.pdb
│   coreclr.dll
│   Imaging.NET.dll.config
│   Imaging.NET.pdb
│   InterCommunication.NET.pdb
│   libwim-15.dll
│   MediaCreationLib.DismOperations.NET.pdb
│   MediaCreationLib.NET.dll.config
│   MediaCreationLib.NET.pdb
│   MediaCreationLib.Planning.NET.pdb
│   Microsoft.Cabinet.NET.pdb
│   Microsoft.Dism.NET.pdb
│   Microsoft.Wim.NET.pdb
│   mscordaccore.dll
│   Privileges.NET.pdb
│   UUPDownload.dll.config
│   UUPDownload.exe
│   UUPDownload.pdb
│   UUPMediaConverterCli.dll.config
│   UUPMediaConverterCli.exe
│   UUPMediaConverterCli.pdb
│   UUPMediaConverterDismBroker.dll.config
│   UUPMediaConverterDismBroker.exe
│   UUPMediaConverterDismBroker.pdb
│   VirtualHardDiskLib.NET.pdb
│   WindowsUpdateLib.NET.dll.config
│   WindowsUpdateLib.NET.pdb
│
├───CDImage
│       cdimage.exe
│
└───runtimes
    └───win-x64
        └───native
            │   aria2c.exe
            │   clrcompression.dll
            │   clrjit.dll
            │   CompDB.NET.pdb
            │   coreclr.dll
            │   Imaging.NET.dll.config
            │   Imaging.NET.pdb
            │   InterCommunication.NET.pdb
            │   libwim-15.dll
            │   MediaCreationLib.DismOperations.NET.pdb
            │   MediaCreationLib.NET.dll.config
            │   MediaCreationLib.NET.pdb
            │   MediaCreationLib.Planning.NET.pdb
            │   Microsoft.Cabinet.NET.pdb
            │   Microsoft.Dism.NET.pdb
            │   Microsoft.Wim.NET.pdb
            │   mscordaccore.dll
            │   Privileges.NET.pdb
            │   UUPDownload.dll.config
            │   UUPDownload.exe
            │   UUPDownload.pdb
            │   UUPMediaConverterCli.dll.config
            │   UUPMediaConverterCli.exe
            │   UUPMediaConverterCli.pdb
            │   UUPMediaConverterDismBroker.dll.config
            │   UUPMediaConverterDismBroker.exe
            │   UUPMediaConverterDismBroker.pdb
            │   VirtualHardDiskLib.NET.pdb
            │   WindowsUpdateLib.NET.dll.config
            │   WindowsUpdateLib.NET.pdb
            │
            └───CDImage
                    cdimage.exe


```

**Comment by Tekkie-Boy** [comment]
For the uupmediaconvertercli.exe only the file: libwim-15.dll has to be in the native folder.

But I've also asked myself why the files are not packaged correctly right away.

Maybe there is a reason? idk

**Comment by andrewbaker-uk** [comment]
Copied all the files as a belt and braces thing will go back tomorrow and try again with just the dll in the native folder

**Comment by Tekkie-Boy** [comment]
You can also leave the files in the folder. 

I just wanted to say that the libwim-15.dll file in the folder is sufficient.

**Comment by gus33000** [comment]
Thanks for the report, looks like an issue with the build system overall, will look into it
