### ISSUE TITLE
Native error 1314: "A required privilege is not held by the client." when converting ISO files without an edition parameter when running as standard user

### ISSUE THREAD

**Issue by truefriend-cz** [gus33000/UUPMediaCreator#29]
After update to new version script ended with error.

Run steps:
1. `UUPDownload -s EnterpriseG -v 10.0.19043.985 -t amd64 -r External -c vb_release -o Download -l en-US`
2. `for /f %f in ('dir /b .\Download\') do UUPMediaConverterCli.exe %CD%\Download\%f %CD%\ISO\Windows_10_amd64_en-US.iso en-US`

```
[   Error   ] An error occured!
[   Error   ] System.InvalidOperationException: Native error 1314.
   at VirtualHardDiskLib.VHDUtilities.MountVirtualDisk(String vhdfile)
   at VirtualHardDiskLib.VirtualDiskSession..ctor(Int64 sizeInGB, Boolean delete, String existingVHD)
   at MediaCreationLib.MediaCreator.HandleEditionPlan(EditionTarget targetEdition, String UUPPath, String MediaPath, String LanguageCode, String InstallWIMFilePath, String WinREWIMFilePath, CompressionType CompressionType, String VHDMountPath, String CurrentBackupVHD, ProgressCallback progressCallback)
   at MediaCreationLib.MediaCreator.CreateISOMediaAdvanced(String ISOPath, String UUPPath, String LanguageCode, Boolean IntegrateUpdates, CompressionType CompressionType, ProgressCallback progressCallback)
   at UUPMediaConverterCli.Program.Main(String[] args)
```

How i can fix this?

**Comment by gus33000** [comment]
Native error 1314 is "A required privilege is not held by the client."

Considering you're calling the converter tool without an edition parameter, make sure to run your command prompt as administrator.

**Comment by truefriend-cz** [comment]
I will running as Administrator

![image](https://user-images.githubusercontent.com/7845691/118391637-9d173d80-b635-11eb-9f5f-55eadf18f647.png)

**Comment by gus33000** [comment]
That's a totally different issue on its own, please file a separate issue for this.
