### ISSUE TITLE
One or more errors occurred. (Value cannot be null. (Parameter 'source'))

### ISSUE THREAD

**Issue by Alee14** [gus33000/UUPMediaCreator#61]
Hello so I tried to download the latest insider build for Windows 11, it gave me this.
Also not sure if this is a bug with UUPMediaCreator or something is up with Microsoft's servers.

```
AleeNAS/Technology/UUPMediaCreator on ☁️  (us-east-2) took 4s 
❯ ./UUPDownload -s Professional -v 10.0.22000.51 -r External -b Dev -c co_release -t amd64
[15:49:55][Information] UUPDownload 0.3.0.6 - Download from the Microsoft Unified Update Platform
[15:49:55][Information] Copyright (c) Gustave Monce and Contributors
[15:49:55][Information] https://github.com/gus33000/UUPMediaCreator

[15:49:55][Information] This program comes with ABSOLUTELY NO WARRANTY.
[15:49:55][Information] This is free software, and you are welcome to redistribute it under certain conditions.

[15:49:55][Information] This software contains work derived from libmspack licensed under the LGPL-2.1 license.
[15:49:55][Information] (C) 2003-2004 Stuart Caie.
[15:49:55][Information] (C) 2011 Ali Scissons.

[15:49:55][Information] Checking for updates...
[15:49:58][Information] Title: Cumulative Update for Windows 11 (10.0.22000.51) (KB5004564)
[15:49:58][Information] Description: Install this update to resolve issues in Windows. For a complete listing of the issues that are included in this update, see the associated Microsoft Knowledge Base article for more information. After you install this item, you may have to restart your computer.
[15:49:58][Information] Gathering update metadata...
[15:50:05][Information] Build String: 10.0.22000.51 (co_release_svc_prod2.210617-2050)
[15:50:05][Information] Languages: bg-bg, ar-sa, ru-ru, fr-fr, pt-br, lv-lv, hu-hu, fi-fi, he-il, sk-sk, cs-cz, pl-pl, it-it, sl-si, nl-nl, et-ee, uk-ua, ro-ro, th-th, de-de, da-dk, nb-no, es-es, en-us, tr-tr, lt-lt, el-gr, sv-se, pt-pt, zh-tw, en-gb, ja-jp, sr-latn-rs, fr-ca, hr-hr, es-mx, zh-cn, ko-kr
[15:50:05][Information] Parsing CompDBs...
[15:50:09][   Error   ] Something happened.
[15:50:09][   Error   ] One or more errors occurred. (Value cannot be null. (Parameter 'source'))
[15:50:09][   Error   ]    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at UUPDownload.DownloadRequest.Process.ParseOptions(DownloadRequestOptions opts)
[15:50:09][   Error   ] Value cannot be null. (Parameter 'source')
[15:50:09][   Error   ]    at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaCreationLib.Planning.NET.ConversionPlanBuilder.GetEditionsThatCanBeTargetedUsingPackageDowngrade(String UUPPath, HashSet`1 compDBs, IEnumerable`1 availableCanonicalEditions, List`1 possibleEditionUpgrades, ProgressCallback progressCallback)
   at MediaCreationLib.Planning.NET.ConversionPlanBuilder.GetTargetedPlan(String UUPPath, HashSet`1 compDBs, String EditionPack, String LanguageCode, Boolean IncludeServicingCapableOnlyTargets, List`1& EditionTargets, ProgressCallback progressCallback)
   at MediaCreationLib.Planning.NET.ConversionPlanBuilder.GetTargetedPlan(HashSet`1 compDBs, String EditionPack, String LanguageCode, Boolean IncludeServicingCapableOnlyTargets, List`1& EditionTargets, ProgressCallback progressCallback)
   at UUPDownload.BuildTargets.GetTargetedPlanAsync(UpdateData update, String LanguageCode, String editionPkg)
   at UUPDownload.DownloadRequest.Process.ProcessUpdateAsync(UpdateData update, String pOutputFolder, MachineType MachineType, String Language, String Edition, Boolean WriteMetadata)
   at UUPDownload.DownloadRequest.Process.PerformOperation(DownloadRequestOptions o)
```

**Comment by Alee14** [comment]
Latest update fixed it
